### ISSUE TITLE
Improve the BE breadcrumb accessibility

### ISSUE THREAD

**Issue by Aybee** [contao/core-bundle#1039]
Hallo Leo,

mit ein paar kleinen CSS-Änderungen sähe die Breadcrumb im BE noch genauso aus, aber man müsste dann mit der Maus oder dem Finger nicht mehr so genau ziehlen, weil der Linktext dann in der ganzen Höhe (34px, momentan 15px) klickbar wäre.
```css
#tl_breadcrumb {
	margin: 0 0 12px;
	padding: 9px 6px;
	padding: 0 6px; /* new */
	overflow: hidden;
	background: #fffce1;
	border: 1px solid #d68c23;
	line-height: 34px; /* new */
}
/* new */
#tl_breadcrumb li a {
	display: inline-block;
}
```

**Comment by leofeyer** [comment]
Finde ich gut. Und wenn wir schon dabei sind, sollten wir noch `>` durch `›` ersetzen, damit es konsistent mit dem `h1.main_headline`-Breadcrumb ist.

**Comment by Aybee** [comment]
Finde ich gut, dass du das gut findest 😄 

Ach, ist mir nicht aufgefallen, dass dies andere Zeichen sind.

Ich habe grad heute auch noch an anderen Stellen gesehen, dass der klicksensitive Bereich optimiert werden könnte. Z.B. in der Dateiverwaltung bei den Pluszeichen zum Aufklappen und dem Dateinamenlink. Hast du das CSS selber gemacht? Sonst könnte ja evtl. der Entwickler nochmal hingehen und dies optimiert nacharbeiten. Habe so im Hinterkopf, dass dies mal ne Auftragsarbeit war, oder vertue ich mich da mit contao.org?

**Comment by agoat** [comment]
+1 für größere Klick-Bereiche.

**Comment by leofeyer** [comment]
Geändert in 456e9c8b501d128c1bba76a99ec674a8e463f6a1. Vielen Dank @Aybee.

> dass dies mal ne Auftragsarbeit war, oder vertue ich mich da mit contao.org?

Das galt nur für contao.org und nicht für das Backend. Insofern kannst Du gerne entsprechende Pull-Requests erstellen.

**Comment by leofeyer** [comment]
Leider funktioniert die Änderung doch nicht:

<img width="367" alt="" src="https://user-images.githubusercontent.com/1192057/29963053-c7e81df0-8f05-11e7-8de6-b7d1f1856924.png">

Ich habe in 36e6743a404e4b84fb0928e50ca32cb95940a245 eine Kompromisslösung implementiert:

<img width="406" alt="" src="https://user-images.githubusercontent.com/1192057/29963075-df1c0aea-8f05-11e7-99e8-ce111175fb6f.png">

**Comment by Aybee** [comment]
Was meinst du mit "funktioniert doch nicht"? ist dir der vertikale Abstand zu groß?

Ich finde, das Padding ist Verschwendung von Fläche.

Zu den Bildern:
**1**. Original
**2**. Deine Lösung
```css
#tl_breadcrumb {
  padding: 4px 6px;
  line-height: 24px;
}
```
**3**. Meine mit korrigiertem vertikalem Abstand.
```css
#tl_breadcrumb {
  padding: 0 6px;
  line-height: 28px;
}
```
**4**. Wie 3 mit line-height:31px. Damit hätte die Breadcrumb die gleiche Höhe wie das Original.
![bildschirmfoto am 2017-09-04 um 21 34 40](https://user-images.githubusercontent.com/1143013/30037211-0d58408a-91b9-11e7-8d16-4d70f72e093d.png)
![bildschirmfoto am 2017-09-04 um 21 34 48](https://user-images.githubusercontent.com/1143013/30037212-0d59c4c8-91b9-11e7-838a-38024d20e6b1.png)
![bildschirmfoto am 2017-09-04 um 21 34 55](https://user-images.githubusercontent.com/1143013/30037213-0d5b76d8-91b9-11e7-8112-ae2869915e69.png)
![bildschirmfoto am 2017-09-04 um 21 47 31](https://user-images.githubusercontent.com/1143013/30037398-c1849c2e-91ba-11e7-8a7f-cd2cf3180064.png)

Ab Bild 3 habe ich noch das vertikale Padding der LIs für Responsive entfernt. Das wird dann nicht mehr benötigt.
```css
@media (max-width:767px) {
/*
  #tl_breadcrumb li {
    padding: 3px;
  }
*/
}
```
