### ISSUE TITLE
Do not hardcode bundles in AppKernel

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#107]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/29) by @aschempp
Friday Oct 31, 2014 at 22:42 GMT

Hardcoding the `FrameworkBundle` in the `AppKernel` will result in an exception, if the `FrameworkBundle` is added to the autoload.json

```
Fatal error: Uncaught exception 'LogicException' with message 'Trying to register two bundles with the same name "FrameworkBundle"'
```

We should only use the bundle autoloading and add the basic requirements to the autoload.json. This would also mean we can change them without affecting the distribution repo.
I can provide PRs if you prefer that.

**Comment by importer** [comment]
> <a href="https://github.com/tristanlins"><img src="https://avatars.githubusercontent.com/u/343404?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @tristanlins
Saturday Nov 01, 2014 at 13:27 GMT

> if the `FrameworkBundle` is added to the autoload.json

You did something wrong, if you add "system related mandatory" bundles to your `autoload.json`.
But this can be solved simply, just check if the autoloaded bundle class is already registered to the kernel.

https://github.com/contao/module-core/blob/feature/symfony2/src/HttpKernel/ContaoKernel.php#L112

```php
    protected function generateBundlesMap(array $hardcodedBundles)
    {
        $hardcodedBundleClasses = array_map(
            function(BundleInterface $bundle) { return get_class($bundle); },
            $hardcodedBundles
        );

        $autoloader = new BundleAutoloader($this->getRootDir(), $this->getEnvironment());
        $bundlesMap = $autoloader->load();

        $bundlesMap = array_filter(
            $bundlesMap,
            function (Config $bundleMap) use ($hardcodedBundleClasses) {
                return !in_array($bundleMap->getClass(), $hardcodedBundleClasses);
            }
        );

        return $bundlesMap;
    }
```

I have made the proposal to support a `src/autoload.json` for local / project specific autoload configuration on our meeting. The conclusion was that everyone can manipulate the `AppKernel` and write local bundles directly into the kernel. If we propose to not put bundles directly into the `AppKernel` we need to provide a local `autoload.json`.

BTW: what happen when two bundles define the same autoload bundle in their `autoload.json`???

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Saturday Nov 01, 2014 at 20:20 GMT

I am with @tristanlins on this.

> BTW: what happen when two bundles define the same autoload bundle in their `autoload.json`???

We should definitely test this and apply `array_unique` if necessary.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Sunday Nov 02, 2014 at 07:36 GMT

Multiple requirements with the same name should not be a problem, because we use array keys for the bundle names.

To me, the `FrameworkBundle` is a dependency of the `ContaoCoreBundle`. I agree we don't need a `src/autoload.json`, because a developer can add his bundle in `AppKernel` if there is a custom one. But then he also knows about the dependencies and wether they are already loaded. But an extension developer does not know if you removed `FrameworkBundle` from the `AppKernel`.

I can't see any advantage of including it in the kernel, I can only see potential issues.

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Wednesday Nov 05, 2014 at 09:26 GMT

> To me, the `FrameworkBundle` is a dependency of the `ContaoCoreBundle`.

No, I don't agree. The `FrameworkBundle` is required to run the application (just like the `SensioFrameworkBundle` etc.). And any application related bundle should be hardcoded in the `AppKernel`.

This also applies to any bundle that we are shipping pre-configured in the `config.yml` file, e.g. Doctrine and SwiftMailer.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Wednesday Nov 05, 2014 at 09:31 GMT

If you follow that logic, it would mean the `CoreBundle` is also a requirement to run the application... but this can't be included, because the autoloader would choke (with the same issue as I described).

Also, if we add ORM later, would that mean we need to add it to the `AppKernel` because it will now be an application requirement?

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Wednesday Nov 05, 2014 at 09:33 GMT

Probably. We need to discuss this.

**Comment by importer** [comment]
> <a href="https://github.com/tristanlins"><img src="https://avatars.githubusercontent.com/u/343404?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @tristanlins
Wednesday Nov 05, 2014 at 09:49 GMT

`FrameworkBundle` is a little special, because it provide the distribution setup. Well it's not required to run a distribution, but it provide the basic "framework" to run the distribution.

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Wednesday Nov 05, 2014 at 10:04 GMT

I also tend to think that if the core bundle adds e.g. Doctrine, we should not provide its configuration in the `config.yml` file. We would otherwise configure bundles from which we don't know if they are enabled at all (e.g. removing the core bundle would also remove Doctrine if it were a core bundle dependency).

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Wednesday Nov 05, 2014 at 10:05 GMT

Do you mean the `config.yml` of the bundle or the app folder?

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Wednesday Nov 05, 2014 at 10:06 GMT

Of the app folder (see #30).

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Wednesday Nov 05, 2014 at 10:18 GMT

I think so too. Not sure if there are other options than a prepent bundle extension. It would also correctly mean extensions should add an autoload statement on the `CoreBundle`, which is correct in my opinion. They should also add the `CoreBundle` to their composer.json to make sure the Contao version fits.

**Comment by importer** [comment]
> <a href="https://github.com/tristanlins"><img src="https://avatars.githubusercontent.com/u/343404?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @tristanlins
Wednesday Nov 05, 2014 at 11:01 GMT

It is possible to prepent the default connection. You can overwrite or extend it in the `app/config/config.yml`.
Here is an example for the doctrine connection:

`@CoreBundle\Resources\config\prepend.yml`
```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
```

`app/config/config.yml`
```yaml
doctrine:
    dbal:
        connections:
            database2:
                driver:   "%database2_driver%"
                host:     "%database2_host%"
                dbname:   "%database2_name%"
                user:     "%database2_user%"
                password: "%database2_password%"
```

After normalisation, the result would be:
```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
            database2:
                driver:   "%database2_driver%"
                host:     "%database2_host%"
                dbname:   "%database2_name%"
                user:     "%database2_user%"
                password: "%database2_password%"
```
