### ISSUE TITLE
Include website title in nav bar

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1121]
We use the `websiteTitle` to output the version of a platform quite often, like so:

```yaml
contao:
    localconfig:
        websiteTitle: "Website title (v %platform_version%)"
```

On every update we dynamically adjust the `platform_version` parameter from git tags but that's a detail 😄 

Would you accept displaying the website title there by default so it would look something like this:

![bildschirmfoto 2017-10-02 um 17 46 12](https://user-images.githubusercontent.com/481937/31086480-34dbb94c-a79a-11e7-9e8f-4e74f5140db1.png)

If you think that's a bad idea to output the title there, would you adjust `be_main` so that it gets a block here so I don't have to override all of it?

```html
        <div class="version">
          <?= $this->version ?><br><?= $this->learnMore ?>
        </div>
```
