### ISSUE TITLE
Add a service for alias generation

### ISSUE THREAD

**Issue by m-vo** [contao/core-bundle#1305]
There is a save callback `generateAlias` registered in `tl_article`, `tl_page` and `tl_form` with quite some repeated code. And I keep repeating myself aswell when I'm using aliases in my  extensions. :-)

What do you think about adding a generic service as a replacement? I think that could be handy.

```yaml
   services:
        contao.datacontainer.generate_alias:
            class: Contao\DataContainer\AliasGenerator
            arguments: ['@contao.slug.generator', 'title']
```

There would be the need to differentiate a bit of course (e.g. `generatePageAlias` vs. `generateArticleAlias`...) or a inspection of the dca parameter. The source field could be injected as a constructor parameter. If someone needs custom functionality it's easy to extend the class and register a new service. 

(Btw.: I'm pro moving the callback code out of the dca files. Are there any BC breaks involved in doing so?)
