### ISSUE TITLE
Make invisible content elements visible in BE preview

### ISSUE THREAD

**Issue by Aybee** [contao/core-bundle#1330]
Wenn man CEs fürs FE erstellt, welche über die Klasse `invisible` nur für Screenreader sichtbar geschaltet werden, dann sieht man sie auch nicht in der Vorschau im BE.

Evtl. könnte man die Klasse `invisible` fürs BE CSS ändern in `be_invisible` o.ä.

Ich habe das vorhandene CSS fürs BE mal angepasst, sodass diese Elemente in der Vorschau sichtbar sind.
![bildschirmfoto am 2018-01-20 um 22 07 14](https://user-images.githubusercontent.com/1143013/35188145-dc1f42ae-fe30-11e7-9149-92363ece0f1c.png)
```css
.tl_content .invisible {
  border: inherit;
  clip: inherit;
  height: inherit;
  margin: 0 0 1em;
  overflow: inherit;
  padding: 20px 0 3px;
  position: relative;
  width: inherit;
  background-color: rgba(75, 133, 186, .1);
}
.tl_content .invisible:after {
  content: "Screenreaders only";
  position: absolute;
  top: 0px;
  right: 3px;
  color: #4b85ba;
  font-weight: normal;
  font-style: italic;
}
```

**Comment by leofeyer** [comment]
Würde das nicht auch alle Elemente unterhalb von `.tl_content` sichtbar machen, die wir im BE für Screenreader zusätzlich ausgeben? Zum Beispiel die Button-Titles?

**Comment by Aybee** [comment]
Ich hatte da nichts gesehen. Ich habe jetzt nochmal ganz aggressiv angesetzt mit zusätzlich
```css
.tl_content .invisible:after {
  background-color: red;
  min-width: 300px;
  min-height: 200px;
  z-index: 999999999;
}
```
Ich kann da sonst nirgendwo was entdecken.
