### ISSUE TITLE
Adapt the config.yml instead of initconfig.php

### ISSUE THREAD

**Issue by netzarbeiter** [contao/core-bundle#1437]
If I want to add some specific CSS for the backend, the way I know is:

Writing the following lines in the `system/config/initconfig.php`

```php
if(TL_MODE == 'BE')
{
    $GLOBALS['TL_CSS'][]        = 'layout/css/backend.css';
}
```

Would it not be nice if we could reference to the file in the config.yml?

e.g.
```yml
contao:
    additional_backend_css:
        - layout/css/backend.css
```

**Comment by Toflar** [comment]
I think this is a valid use case. It's pretty complicated right now for non-developers to customize the back end layout a little. I think one css file would be enough to cover 90% of all use cases and more complex ones should use hooks.

**Comment by bezin** [comment]
I like this. We sometimes develop projects with Kirby, and they solve it exactly that way: https://getkirby.com/docs/developer-guide/panel/css. Really handy for minor changes.

**Comment by aschempp** [comment]
I could generally agree to something like that, but I think it should be something like this:

```yml
contao:
    backend:
        additional_css: 'layout/css/backend.css'
        additional_js: 'layout/js/backend.js'
```

I don't think there is a need for multiple files, and we should allow both CSS and JS.
