### ISSUE TITLE
No two columns view in Edge

### ISSUE THREAD

**Issue by Aybee** [contao/core-bundle#1481]
Im Edge werden die w50 Widgets nicht nebeneinander angezeigt, sondern untereinander. Das liegt an dem Width der Flexitems. Width reicht in den Browsern nicht, um eine exakte Breite einzustellen. Dazu benötigt es z.B. `min-width`. Hier die Korrektur, wobei das 100% bei #main für die Ausdehnung auf den noch zur Verfügung stehenden Platz sorgt:
```css
#left {
  float: left;
  /* width: 225px; */
  min-width: 225px; /* new */
  min-height: calc(100vh - 40px);
  background: #0f1c26;
  display: flex;
  flex-direction: column;
}
#main {
  float: left;
  /* width: calc(100% - 225px); */
  width: 100%;
  min-height: calc(100vh - 40px);
  background: #eaeaec;
}
```
