### ISSUE TITLE
Increase the line height for input fields

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#501]
The line height for input fields should be increased slightly since some large letters become truncated a little bit (FF 46.0.1)

![contao_input_line_height](https://cloud.githubusercontent.com/assets/1218766/15435893/4059f62c-1ebf-11e6-92f2-25831433c570.png)

[Contao 4.2.0-RC1]

**Comment by leofeyer** [comment]
I cannot reproduce it in FF on Mac OS. You are using Windows, aren't you?

**Comment by xchs** [comment]
> You are using Windows, aren't you?

Yes.

**Comment by leofeyer** [comment]
I don't have Windows, so I cannot test it. It is a Firefox only issue or are Chrome and IE affected, too?

**Comment by xchs** [comment]
It is actually a Firefox only issue (I know, the "new IE", as you always used to say :smile:).

**Comment by fritzmg** [comment]
The problem is the missing normalization of `<input>` fields. Contao uses
```css
line-height: 1;
```
on the `<body>`. However, in Chrome, this is overwritten for `<input>` fields (and other tags) by its internal user agent stylesheet and set to
```css
line-height: normal;
```
This is missing in FireFox, thus `line-height: 1;` of the `<body>` stays in effect, which cuts off the text. [normalize.css](https://necolas.github.io/normalize.css/) includes the following style for example:
```css
/**
 * Address Firefox 4+ setting `line-height` on `input` using `!important` in
 * the UA stylesheet.
 */

input {
  line-height: normal;
}
```

**Comment by leofeyer** [comment]
We are already applying `font: inherit`, so I guess we have to add the line height fix.

**Comment by leofeyer** [comment]
Fixed in 40356b380accfc808d378561d4eb11602707b871.

**Comment by fritzmg** [comment]
> We are already applying font: inherit, so I guess we have to add the line height fix.

Yes, but you overwrite it with `line-height:inherit;` https://github.com/contao/core-bundle/blob/4.2.0-RC1/src/Resources/contao/themes/flexible/src/basic.css#L54
```css
input,textarea,select,button {
	font:inherit;
	color:inherit;
	line-height:inherit;
}
```
This inherits `line-height:1;` from the `<body>`.
