### ISSUE TITLE
Custom URL-Suffix?

### ISSUE THREAD

**Issue by ADoebeling** [contao/core-bundle#629]
In Contao3 war es [möglich ](https://github.com/contao/core/issues/4031#issuecomment-4286018) einen individuellen URL-Suffix festzulegen, wir haben das gerne genutzt um den Suffix vollständig weg zu lassen.:

![image](https://cloud.githubusercontent.com/assets/10674780/20481321/d08e5bf8-afe6-11e6-8177-9ee73d98f286.png)

Auch im Netz finden sich [hierzu ](http://www.novo-online.de/blog/2015/07/16/contao-website-ohne-html-in-der-url/) [ein ](http://www.dierssengmbh.de/know-how-detail/items/contao-url-mit-und-ohne-suffix-html-erreichbar-machen.html) [paar ](https://nic3.de/-/contao-url-ohne-html) Blog-Artikel.

Diese Möglichkeit scheint augenscheinlich in Contao4 entfallen zu sein.
Gibt es eine Möglichkeit dies dennoch weiter zu nutzen?

**Comment by bytehead** [comment]
Du kannst diesen Suffix über die Datei `app/config.yml` konfigurieren:
```yaml
# Contao configuration
contao:
    # Required parameters
    prepend_locale: false
    encryption_key: "%kernel.secret%"

    # Optional parameters
    url_suffix: ''
```

Siehe Contao 4 Core Bundle Readme: https://github.com/contao/core-bundle/blob/master/README.md#installation

**Comment by ADoebeling** [comment]
Besten Dank @bytehead & sorry, dass ich das nicht selbst gefunden habe.

**Comment by rustykowski** [comment]
in der Managed Edition geht das auf diesem Weg offenbar nicht? Habe in `app/config/parameters.yml` versucht, ohne Erfolg:

```
parameters:
    ...
    prepend_locale: false
    url_suffix: '/'
```
