### ISSUE TITLE
enum // Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

### ISSUE THREAD

**Issue by fgrosswig** [contao/core-bundle#715]
hello, we are getting the enum error in contao 4.3.5 again... how this may be fixed?

 ```
$dbType = strtolower($dbType);
        if (!isset($this->doctrineTypeMapping[$dbType])) {
            throw new \Doctrine\DBAL\DBALException("Unknown database type ".$dbType." requested, " . get_class($this) . " may not support it.");
        }
        return $this->doctrineTypeMapping[$dbType];
```

```
        $this->setLengthAndPrecisionByType($type, $dbType, $length, $scale, $precision, $fixed);
        $type = $this->container->get('database_connection')->getDatabasePlatform()->getDoctrineTypeMapping($type);
        $length = (0 === (int) $length) ? null : (int) $length;
        if (preg_match('/default (\'[^\']*\'|\d+)/', $def, $match)) {
```

```
  if (isset($definitions['TABLE_FIELDS'])) {
                foreach ($definitions['TABLE_FIELDS'] as $fieldName => $sql) {
                    $this->parseColumnSql($table, $fieldName, strtolower(substr($sql, strlen($fieldName) + 3)));
                }
            }
```

```
'exit_state' => array
        (
            'label'                   => &$GLOBALS['TL_LANG']['tl_table']['exit_state'],
            'inputType'               => 'text',
            'exclude'                 => true,
            'eval'                    => array(
                'mandatory'=>false,
                'tl_class'=>'w50'
            ),
            'sql'                     => "enum( 'none', 'normal', 'timedout' ) default 'none'",
        )
```

**Comment by fgrosswig** [comment]
we have found a way:

```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                host: "%database_host%"
                port: "%database_port%"
                user: "%database_user%"
                password: "%database_password%"
                dbname: "%database_name%"
                charset: UTF8
                mapping_types:
                    enum: string
```
