### ISSUE TITLE
No database selected during /contao/install when using download archive

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#736]
1. Download the Contao Managed Edition `4.3.7` from contao.org
2. Extract and run `/contao/install`.
3. Accept the license.

On the subsequent screens (entering the install tool password plus entering the database details) the following error message will be displayed at the bottom of the page:
```
Fatal error: Uncaught PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected in \vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:104 
Stack trace: 
#0 \vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(104): PDO->query('SHOW FULL TABLE...') 
#1 \vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('SHOW FULL TABLE...') 
#2 \vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SHOW FULL TABLE...', Array, Array) 
#3 \vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\AbstractSchemaManager.php(219): Doctrine\DBAL\Connection->fetchAll('SHOW FULL TABLE...') 
#4 \vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\AbstractSchemaManager.php(207): Doctrine\DBAL\Schema\AbstractSchemaManager->listTableNames() 
#5 \vendor\contao\core-bundle\src\EventListener\ in \vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php on line 99
```
Testing environment:

* Windows 10
* XAMPP
* PHP 7.1.1 (FastCGI)

Not sure if this ticket belongs to the core-bundle, the installation-bundle or the managed-edition. The error only seems to happen with the managed edition during installation and the error is genereated within the EventListener of the core-bundle.

The error message is appended after the `</html>` from the install tool.

**Comment by leofeyer** [comment]
I cannot reproduce the issue and it has not occurred at my presentation on the Contao Nordtag, either.

**Comment by fritzmg** [comment]
Yeah haven't seen any other reports yet either. May be it is Windows specific, I'll try to debug.

**Comment by fritzmg** [comment]
The error happens here:
```php
    /**
     * Checks whether the controller can be run.
     *
     * @return bool
     */
    private function canRunController()
    {
        /** @var Config $config */
        $config = $this->framework->getAdapter(Config::class);
        return $config->isComplete()
            && !$config->get('disableCron')
            && $this->connection->getSchemaManager()->tablesExist(['tl_cron'])
        ;
    }
```
https://github.com/contao/core-bundle/blob/4.3.7/src/EventListener/CommandSchedulerListener.php#L73

The `CommandSchedulerListener` is querying a table - but that won't be possible during `/contao/install` if the database connection has not been set up yet.

@leofeyer how did you test? This problem only occurs if you _download_ Contao from contao.org. It won't occur with `composer create-project`, since the database connection will be set up during that process.

**Comment by leofeyer** [comment]
This has been fixed in e5527fba48d30ced12cdc880907130dce6015bcc already.

**Comment by fritzmg** [comment]
This is still happening in Contao `4.3.8` (Managed Edition downloaded from contao.org).

**Comment by fritzmg** [comment]
```php
$this->connection->isConnected();
```
returns `true`, even though no database connection is present.

**Comment by fritzmg** [comment]
`Doctrine\DBAL\Connection::isConnected`  returns
```php
/**
 * Whether an actual connection to the database is established.
 *
 * @return boolean
 */
public function isConnected()
{
    return $this->_isConnected;
}
```
https://github.com/doctrine/dbal/blob/v2.5.12/lib/Doctrine/DBAL/Connection.php#L551

and this variable will be set to true here:
```
$this->_conn = $this->_driver->connect($this->_params, $user, $password, $driverOptions);
$this->_isConnected = true;
```
https://github.com/doctrine/dbal/blob/v2.5.12/lib/Doctrine/DBAL/Connection.php#L361

I am guessing that a connection can already be established with these default parameters:
```yml
parameters:
    database_host: localhost
    database_port: ~
    database_user: ~
    database_password: ~
    database_name: ~

# Doctrine configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                host: "%database_host%"
                port: "%database_port%"
                user: "%database_user%"
                password: "%database_password%"
                dbname: "%database_name%"
                charset: UTF8
```
https://github.com/contao/manager-bundle/blob/4.3.8/src/Resources/contao-manager/doctrine.yml

However, you are of course not able to do anything with that connection.
