### ISSUE TITLE
Honeypot anti-spam: add an option to (temporary) show the captcha field

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#879]
It could be helpful if there was an option in the "Security question" form field settings to (temporay) show the captcha field in the front end so that it can be styled more easily.

**Comment by ausi** [comment]
You can use this CSS code to show the captcha field temporarily:

```css
.widget-captcha { display: block !important }
```
