### ISSUE TITLE
Text in Formularfeldern im Backend in Chrome nicht vertikal mittig

### ISSUE THREAD

**Issue by Mynyx** [contao/core-bundle#962]
Text in Formularfeldern im Backend ist in Chrome nicht vertikal mittig ausgerichtet.

Chrome:
![image](https://user-images.githubusercontent.com/1632642/28186180-76a7fa6c-681a-11e7-9f01-1ae8b46cf9b4.png)

Firefox:
![image](https://user-images.githubusercontent.com/1632642/28186148-5640bcaa-681a-11e7-8dba-f8fd75c035cb.png)

**Comment by leofeyer** [comment]
Kann ich nicht reproduzieren.

<img width="640" alt="" src="https://user-images.githubusercontent.com/1192057/28210772-68c3a7a0-6899-11e7-9471-229a5b70dab2.png">

Windows oder Mac OS? Browser-Cache geleert?

**Comment by patrickjDE** [comment]
Kann ich unter Windows nachvollziehen, ist aber meiner Meinung nach kein Fehler sondern einfach Definitionssache. Firefox zentriert vertikal anhand der cap-height, Chrome anhand der x-height.

![Typography_Line_Terms](https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Typography_Line_Terms.svg/410px-Typography_Line_Terms.svg.png)

Wobei man natürlich darüber streiten kann, dass das Verhalten von Chrome vor allem bei kurzen Worten und komplettem Uppercase suboptimal ist, da der Text dann optisch nach oben verschoben wirkt...

**Comment by leofeyer** [comment]
Ist aber trotzdem nicht so schön. Und warum macht das Chrome für Mac bei mir nicht?

**Comment by patrickjDE** [comment]
Eventuell nutzt Chrome unter Mac OS-Routinen für das Font-rendering?
Bei Chromium unter Debian bietet sich z. B. das selbe (verschobene) Bild wie bei Chrome unter Windows.

![chromium-debian](https://user-images.githubusercontent.com/6651001/28223079-3ed60538-68ca-11e7-925f-d4df7928e50f.png)

**Comment by m-vo** [comment]
Kann ich bestätigen. Es liegt an der Font (s. auch siehe: https://stackoverflow.com/questions/11726442/font-rendering-line-height-issue-on-mac-pc-outside-of-element). 

original (Lato):
![lato](https://user-images.githubusercontent.com/5305677/28227837-196c293c-68dc-11e7-96b5-b450212dc3d0.png)

mit Arial:
![arial](https://user-images.githubusercontent.com/5305677/28227844-1ca031e8-68dc-11e7-8aa0-021f3687d81a.png)

**Comment by leofeyer** [comment]
Ok, aber wenn es am Font liegt, warum tritt das Problem dann nur in Chrome und nicht in Firefox auf?

**Comment by m-vo** [comment]
Wenn ich es richtig sehe, dann haben die Fonts verschiedene Metriken je nach System eingebettet. Aber du hast schon recht, e

**Comment by fritzmg** [comment]
Dieses Problem haben wir bei praktisch allen Webseiten - zumindest bei Google Fonts (bei eigens erzeugten Font Files von Font Squirrel kann man die Vertical Metrics ggf. verändern). Eine optimale Lösung kenne ich bisher auch nicht...

**Comment by leofeyer** [comment]
Ich schließe das Ticket, da es aktuell nichts gibt, das wir tun können.

**Comment by Aybee** [comment]
Bei mir sieht das in allen Browsern nicht vertikal zentriert aus. Was es bei mir in allen Browsern besser macht ist:
```css
.tl_text,
.tl_text_2,
.tl_text_3,
.tl_text_4,
.tl_textarea,
.tl_text_unit,
.tl_text_trbl,
.tl_text_interval {
  /* padding: 5px 6px 6px; */
  padding: 0 6px;
  height: 30px; /* new */
}
/* new */
.tl_textarea {
  padding: 6px;
}
.tl_select,
.tl_mselect,
.tl_select_column,
.tl_select_unit,
.tl_select_interval {
  /* padding: 5px 22px 6px 6px; */
  padding: 0 22px 0 6px;
  height: 30px; /* new */
}
@-moz-document url-prefix() {
  .tl_select,
  .tl_mselect,
  .tl_select_column,
  .tl_select_unit,
  .tl_select_interval {
    padding: 0 18px 0 2px;
  }
}
```
