### ISSUE TITLE
Bug in edit multiple form view - resolve with CSS

### ISSUE THREAD

**Issue by Aybee** [contao/core-bundle#998]
_Betrifft den Modus "Mehrere bearbeiten". Contao 4.4.2._

Wofür ist diese Regel? Wird die benötigt?
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/themes/flexible/src/basic.css#L520-L523
```css
.subpal {
  width:100%;
  float:left;
}
```
Mit dieser Regel ist die Ansicht buggy und die jQuery-Templates können z.B. nicht ausgewählt werden.

Browser: FF, Chrome, Opera, Edge, IE (außer dass im IE die Auswahl möglich ist).

Hier im FF **mit** der Regel:
![bildschirmfoto am 2017-08-03 um 03 33 15](https://user-images.githubusercontent.com/1143013/28918401-61e3f8d0-7849-11e7-8f2a-e4896f9a3a25.png)

Hier im FF **ohne** die Regel:
![bildschirmfoto am 2017-08-03 um 03 34 13](https://user-images.githubusercontent.com/1143013/28918425-7bc4d40e-7849-11e7-858d-fcd63f2090b4.png)
Lösung getestet in FF und Chrome.

**Comment by leofeyer** [comment]
> Wofür ist diese Regel? Wird die benötigt?

Nein, wir fügen nur ab und an gerne sinnlose CSS-Definitionen ein, damit die Datei nicht zu klein wird.

**Comment by Aybee** [comment]
Ist das jetzt einfach nur sarkastisch, oder böse gemeint?

Bei ersterem würde ich antworten "Ja, ist mir auch schon aufgefallen." 😜 

Kann dies denn nun geändert werden?

**Comment by leofeyer** [comment]
> Ist das jetzt einfach nur sarkastisch, oder böse gemeint?

Es ist keinesfalls böse gemeint. Aber einfach löschen können wir die Regel auch nicht. Ich muss mir das ansehen.

**Comment by agoat** [comment]
Also ich kann das nicht nachvollziehen. Allerdings sieht das bei dir auch etwas komisch aus. Es fehlen die `fieldset legend` Sektions überschriften.

Lösche (noch)mal den Browser-Cache. Es hat sich einiges an den CSS-Dateien in der 4.4.er-Version getan.

Bei mir sieht das so aus:
![layout](https://user-images.githubusercontent.com/1402434/28977850-08cc035e-7944-11e7-8cc5-66ede92770f4.jpg)

**Comment by Aybee** [comment]
Beachte den "edit multiple" Modus.

Mehrere bearbeiten, ein Layout auswählen (reicht für den Test), Bearbeiten, alles auswählen, Weiter.

**Comment by agoat** [comment]
> Beachte den "edit multiple form view" Modus

OK, wenn ich im '_edit multiple modus_' bin, dann sieht das bei mir auch so aus.

Ich schätze das liegt u.a. daran, das beim '_edit multiple modus_' keine `fieldset` Elemente verwendet werden. Die Subpaletten werden in ein eigenes `div` Element gerendert (mit der Klassen-Deklaration 'subpal'), damit diese, wie ich vermute, einfach mit AJAX bzw. MooTools erfasst werden können.

**Comment by Aybee** [comment]
Ist ja eigentlich egal, woran dies liegt. Wir müssen erstmal herausfinden, warum da Elemente, die gefloatet werden eine Breite von 100% bekommen, was IHMO keinen Sinn ergibt. Wenn die Regel entfernt würde, wäre ja alles korrekt.

**Comment by agoat** [comment]
> Elemente, die gefloatet werden eine Breite von 100% bekommen, was IHMO keinen Sinn ergibt.

Der Sinn dahinter ist, dass das Element im _flow_ mit den anderen _gefloateten_ Elementen steht und die Subpaletten wohl in einer neuen Zeile anfangen sollen. Schonmal die `float`und `width` Deklaration in der normalen Ansicht deaktiviert?

Allerdings ist dies keine gute CSS-Paxis. 
Das Problem lässt sich ganz einfach mit folgender Änderung im CSS lösen:
```css
.subpal {
  width: 100%;
  clear: both;
}
```

**Comment by Aybee** [comment]
> Schonmal die float und width Deklaration in der normalen Ansicht deaktiviert?

Ja, du auch? Kein Unterschied zu sehen (FF und Chrome getestet). Auf jeden Fall da, wo ich getestet hatte. Packe ich ein `.widget .w50` direkt davor, dann floatet die `.subpal` rechts daneben.

Haupsächlich hier getestet:
```html
<fieldset id="pal_jquery_legend" class="tl_box">
  <legend >jQuery</legend>
  <div class="widget"> <!-- Test mit  w50: float left -->
  </div>
  <div id="sub_addJQuery" class="subpal"> <!-- float left -->
    <div class="widget"></div>
    <div class="w50 widget"> <!-- float left -->
      <h3><label>jQuery source</label></h3>
    </div>
  </div>
</fieldset>
```
Wenn die .subpal immer die volle Breite bekommen soll, dann reicht auch, wenn wir ihr die Klasse .clr geben. clear:both oder width:100% ist dann nicht nötig.

"Im flow stehen", das sagt mir nichts.

**Comment by leofeyer** [comment]
Fixed in 1ac8a9e5eb9db931b8a96cc11469a1f6acc639b8. Thank you guys for debugging.

**Comment by Aybee** [comment]
Wenn ich den Code lese, dann sieht es so aus, als würde jetzt jedes Feld ohne `tl_class` die Klasse `w50` bekommen. Ich kann das mit den Devtools aber nicht sehen. Habe ich den Code richtig interpretiert?

Die Lösung finde ich nicht ganz so gut. Das width:100% ist überflüssig. Besser wäre es gewesen dem `.subpal` zusätzlich die Klasse `clr` zu geben und dann keine Regel für `.subpal`.

Erklärung:
Spielt mal ein wenig mit den `.widget`-Elementen und gibt den Widgets davor und danach oder auch in der .subpal zusätzlich die Klasse `w50`, dann sieht man mit den Devtools, dass die `.subpal` nicht die volle Höhe bekommt, weil sie nicht "gecleart" ist. Außerdem muss erstmal das `height:80px` von `.w50` entfernt werden, damit sich die Höhe automatisch an den Inhalt anpassen kann.

Die bisherige Lösung für die Widgets und `.subpal` sieht so aus:
```css
.widget {
  margin-left: 15px;
  margin-right: 15px;
  position: relative;
}
.w50 {
  width: calc(50% - 30px);
  float: left;
  height: 80px;
}
.clr {
  clear: both;
  display: table;
  width: calc(100% - 30px);
}
.clr:not(.widget) {
  width: 100%;
}
.subpal {
  width: 100%;
  clear: both;
}
```
Besser wäre IMHO dann (mit `clr` auf `subpal`)
```css
.widget {
  padding-left: 15px;
  padding-right: 15px;
  position: relative;
}
.w50 {
  box-sizing: border-box;
  width: 50%;
  float: left;
}
.clr:after {
  clear: both;
  display: table;
}
```
Kommentiert:
```css
.widget {
  padding-left: 15px; /* padding */
  padding-right: 15px; /* padding */
  position: relative;
}
.w50 {
  box-sizing: border-box; /* new */
  width: 50%; /* simple width */
  float: left;
  /*height: 80px;*/
}
.clr:after { /* :after */
  clear: both;
  display: table;
  /*width: calc(100% - 30px);*/
}
/*
.clr:not(.widget) {
  width: 100%;
}
.subpal {
  width: 100%;
  clear: both;
}
*/
```
Je weniger feste Breiten, Höhen und `calc()` desto besser.
